import './main.css'
export const metadata = {
  title: "MA 🖱️",
  description: "Generated by abolfazl_j10",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  );
}